/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminalCapacityRouteImport } from './routes/terminal-capacity'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as OperatorsRouteImport } from './routes/operators'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ImportRouteImport } from './routes/import'
import { Route as CargoRouteImport } from './routes/cargo'
import { Route as IndexRouteImport } from './routes/index'

import { Route as rootRoute } from './routes/__root'
import { Route as ReservationImport } from './routes/reservation'
import { Route as OperatorsImport } from './routes/operators'
import { Route as NotificationsImport } from './routes/notifications'
import { Route as ImportImport } from './routes/import'
import { Route as CargoImport } from './routes/cargo'
import { Route as CapacityImport } from './routes/capacity'
import { Route as AnalyticsImport } from './routes/analytics'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const ReservationRoute = ReservationImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsRoute = OperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const CargoRoute = CargoRouteImport.update({
  id: '/cargo',
  path: '/cargo',
  getParentRoute: () => rootRouteImport,
} as any)

const CapacityRoute = CapacityImport.update({
  id: '/capacity',
  path: '/capacity',
  getParentRoute: () => rootRoute,
} as any)

const AnalyticsRoute = AnalyticsImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/capacity': {
      id: '/capacity'
      path: '/capacity'
      fullPath: '/capacity'
      preLoaderRoute: typeof CapacityImport
      parentRoute: typeof rootRoute
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsImport
      parentRoute: typeof rootRoute
    }
    '/cargo': {
      id: '/cargo'
      path: '/cargo'
      fullPath: '/cargo'
      preLoaderRoute: typeof CargoImport
      parentRoute: typeof rootRoute
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportImport
      parentRoute: typeof rootRoute
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsImport
      parentRoute: typeof rootRoute
    }
    '/operators': {
      id: '/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof OperatorsImport
      parentRoute: typeof rootRoute
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/capacity': typeof CapacityRoute
  '/analytics': typeof AnalyticsRoute
  '/cargo': typeof CargoRoute
  '/import': typeof ImportRoute
  '/notifications': typeof NotificationsRoute
  '/operators': typeof OperatorsRoute
  '/reservation': typeof ReservationRoute
  '/terminal-capacity': typeof TerminalCapacityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/capacity': typeof CapacityRoute
  '/analytics': typeof AnalyticsRoute
  '/cargo': typeof CargoRoute
  '/import': typeof ImportRoute
  '/notifications': typeof NotificationsRoute
  '/operators': typeof OperatorsRoute
  '/reservation': typeof ReservationRoute
  '/terminal-capacity': typeof TerminalCapacityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/capacity': typeof CapacityRoute
  '/analytics': typeof AnalyticsRoute
  '/cargo': typeof CargoRoute
  '/import': typeof ImportRoute
  '/notifications': typeof NotificationsRoute
  '/operators': typeof OperatorsRoute
  '/reservation': typeof ReservationRoute
  '/terminal-capacity': typeof TerminalCapacityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/capacity'
    | '/analytics'
    | '/cargo'
    | '/import'
    | '/notifications'
    | '/operators'
    | '/reservation'
    | '/terminal-capacity'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/capacity'
    | '/analytics'
    | '/cargo'
    | '/import'
    | '/notifications'
    | '/operators'
    | '/reservation'
    | '/terminal-capacity'
  id:
    | '__root__'
    | '/'
    | '/capacity'
    | '/analytics'
    | '/cargo'
    | '/import'
    | '/notifications'
    | '/operators'
    | '/reservation'
    | '/terminal-capacity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CapacityRoute: typeof CapacityRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CargoRoute: typeof CargoRoute
  ImportRoute: typeof ImportRoute
  NotificationsRoute: typeof NotificationsRoute
  OperatorsRoute: typeof OperatorsRoute
  ReservationRoute: typeof ReservationRoute
  TerminalCapacityRoute: typeof TerminalCapacityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminal-capacity': {
      id: '/terminal-capacity'
      path: '/terminal-capacity'
      fullPath: '/terminal-capacity'
      preLoaderRoute: typeof TerminalCapacityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators': {
      id: '/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof OperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargo': {
      id: '/cargo'
      path: '/cargo'
      fullPath: '/cargo'
      preLoaderRoute: typeof CargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CapacityRoute: CapacityRoute,
  AnalyticsRoute: AnalyticsRoute,
  CargoRoute: CargoRoute,
  ImportRoute: ImportRoute,
  NotificationsRoute: NotificationsRoute,
  OperatorsRoute: OperatorsRoute,
  ReservationRoute: ReservationRoute,
  TerminalCapacityRoute: TerminalCapacityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/capacity",
        "/analytics",
        "/cargo",
        "/import",
        "/notifications",
        "/operators",
        "/reservation"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/capacity": {
      "filePath": "capacity.tsx"
    "/analytics": {
      "filePath": "analytics.tsx"
    },
    "/cargo": {
      "filePath": "cargo.tsx"
    },
    "/import": {
      "filePath": "import.tsx"
    },
    "/notifications": {
      "filePath": "notifications.tsx"
    },
    "/operators": {
      "filePath": "operators.tsx"
    },
    "/reservation": {
      "filePath": "reservation.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
