/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReservationRouteImport } from './routes/reservation'
import { Route as OperatorsRouteImport } from './routes/operators'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ImportRouteImport } from './routes/import'
import { Route as HazardousCargoManagerRouteImport } from './routes/hazardous-cargo-manager'
import { Route as HazardousCargoRouteImport } from './routes/hazardous-cargo'
import { Route as CargoRouteImport } from './routes/cargo'
import { Route as CapacityRouteImport } from './routes/capacity'
import { Route as BerthRequestsRouteImport } from './routes/berth-requests'
import { Route as BerthRequestConfirmationRouteImport } from './routes/berth-request-confirmation'
import { Route as BerthRequestAddRouteImport } from './routes/berth-request-add'
import { Route as BerthManagerRouteImport } from './routes/berth-manager'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'

const ReservationRoute = ReservationRouteImport.update({
  id: '/reservation',
  path: '/reservation',
  getParentRoute: () => rootRouteImport,
} as any)
const OperatorsRoute = OperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const HazardousCargoManagerRoute = HazardousCargoManagerRouteImport.update({
  id: '/hazardous-cargo-manager',
  path: '/hazardous-cargo-manager',
  getParentRoute: () => rootRoute,
} as any)
const HazardousCargoRoute = HazardousCargoRouteImport.update({
  id: '/hazardous-cargo',
  path: '/hazardous-cargo',
  getParentRoute: () => rootRouteImport,
} as any)
const CargoRoute = CargoRouteImport.update({
  id: '/cargo',
  path: '/cargo',
  getParentRoute: () => rootRouteImport,
} as any)
const CapacityRoute = CapacityRouteImport.update({
  id: '/capacity',
  path: '/capacity',
  getParentRoute: () => rootRouteImport,
} as any)
const BerthRequestsRoute = BerthRequestsRouteImport.update({
  id: '/berth-requests',
  path: '/berth-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const BerthRequestConfirmationRoute = BerthRequestConfirmationRouteImport.update({
  id: '/berth-request-confirmation',
  path: '/berth-request-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const BerthRequestAddRoute = BerthRequestAddRouteImport.update({
  id: '/berth-request-add',
  path: '/berth-request-add',
  getParentRoute: () => rootRouteImport,
} as any)
const BerthManagerRoute = BerthManagerRouteImport.update({
  id: '/berth-manager',
  path: '/berth-manager',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsImport
      parentRoute: typeof rootRoute
    }
    '/hazardous-cargo-manager': {
      id: '/hazardous-cargo-manager'
      path: '/hazardous-cargo-manager'
      fullPath: '/hazardous-cargo-manager'
      preLoaderRoute: typeof HazardousCargoManagerImport
      parentRoute: typeof rootRoute
    }
    '/hazardous-cargo': {
      id: '/hazardous-cargo'
      path: '/hazardous-cargo'
      fullPath: '/hazardous-cargo'
      preLoaderRoute: typeof HazardousCargoImport
      parentRoute: typeof rootRoute
    }
    '/berth-manager': {
      id: '/berth-manager'
      path: '/berth-manager'
      fullPath: '/berth-manager'
      preLoaderRoute: typeof BerthManagerImport
      parentRoute: typeof rootRoute
    }
    '/berth-requests': {
      id: '/berth-requests'
      path: '/berth-requests'
      fullPath: '/berth-requests'
      preLoaderRoute: typeof BerthRequestsImport
      parentRoute: typeof rootRoute
    }
    '/capacity': {
      id: '/capacity'
      path: '/capacity'
      fullPath: '/capacity'
      preLoaderRoute: typeof CapacityImport
      parentRoute: typeof rootRoute
    }
    '/cargo': {
      id: '/cargo'
      path: '/cargo'
      fullPath: '/cargo'
      preLoaderRoute: typeof CargoImport
      parentRoute: typeof rootRoute
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportImport
      parentRoute: typeof rootRoute
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsImport
      parentRoute: typeof rootRoute
    }
    '/operators': {
      id: '/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof OperatorsImport
      parentRoute: typeof rootRoute
    }
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationImport
      parentRoute: typeof rootRoute
    }
    '/terminal-capacity': {
      id: '/terminal-capacity'
      path: '/terminal-capacity'
      fullPath: '/terminal-capacity'
      preLoaderRoute: typeof TerminalCapacityImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/hazardous-cargo-manager': typeof HazardousCargoManagerRoute
  '/hazardous-cargo': typeof HazardousCargoRoute
  '/berth-manager': typeof BerthManagerRoute
  '/berth-request-confirmation': typeof BerthRequestConfirmationRoute
  '/berth-request-add': typeof BerthRequestAddRoute
  '/berth-requests': typeof BerthRequestsRoute
  '/capacity': typeof CapacityRoute
  '/cargo': typeof CargoRoute
  '/hazardous-cargo': typeof HazardousCargoRoute
  '/import': typeof ImportRoute
  '/notifications': typeof NotificationsRoute
  '/operators': typeof OperatorsRoute
  '/reservation': typeof ReservationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/hazardous-cargo-manager': typeof HazardousCargoManagerRoute
  '/hazardous-cargo': typeof HazardousCargoRoute
  '/berth-manager': typeof BerthManagerRoute
  '/berth-request-confirmation': typeof BerthRequestConfirmationRoute
  '/berth-request-add': typeof BerthRequestAddRoute
  '/berth-requests': typeof BerthRequestsRoute
  '/capacity': typeof CapacityRoute
  '/cargo': typeof CargoRoute
  '/hazardous-cargo': typeof HazardousCargoRoute
  '/import': typeof ImportRoute
  '/notifications': typeof NotificationsRoute
  '/operators': typeof OperatorsRoute
  '/reservation': typeof ReservationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/hazardous-cargo-manager': typeof HazardousCargoManagerRoute
  '/hazardous-cargo': typeof HazardousCargoRoute
  '/berth-manager': typeof BerthManagerRoute
  '/berth-request-confirmation': typeof BerthRequestConfirmationRoute
  '/berth-request-add': typeof BerthRequestAddRoute
  '/berth-requests': typeof BerthRequestsRoute
  '/capacity': typeof CapacityRoute
  '/cargo': typeof CargoRoute
  '/hazardous-cargo': typeof HazardousCargoRoute
  '/import': typeof ImportRoute
  '/notifications': typeof NotificationsRoute
  '/operators': typeof OperatorsRoute
  '/reservation': typeof ReservationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/hazardous-cargo-manager'
    | '/hazardous-cargo'
    | '/berth-manager'
    | '/berth-request-confirmation'
    | '/berth-request-add'
    | '/berth-requests'
    | '/capacity'
    | '/cargo'
    | '/hazardous-cargo'
    | '/import'
    | '/notifications'
    | '/operators'
    | '/reservation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/hazardous-cargo-manager'
    | '/hazardous-cargo'
    | '/berth-manager'
    | '/berth-request-confirmation'
    | '/berth-request-add'
    | '/berth-requests'
    | '/capacity'
    | '/cargo'
    | '/hazardous-cargo'
    | '/import'
    | '/notifications'
    | '/operators'
    | '/reservation'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/hazardous-cargo-manager'
    | '/hazardous-cargo'
    | '/berth-manager'
    | '/berth-request-confirmation'
    | '/berth-request-add'
    | '/berth-requests'
    | '/capacity'
    | '/cargo'
    | '/hazardous-cargo'
    | '/import'
    | '/notifications'
    | '/operators'
    | '/reservation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  HazardousCargoManagerRoute: typeof HazardousCargoManagerRoute
  HazardousCargoRoute: typeof HazardousCargoRoute
  BerthManagerRoute: typeof BerthManagerRoute
  BerthRequestConfirmationRoute: typeof BerthRequestConfirmationRoute
  BerthRequestAddRoute: typeof BerthRequestAddRoute
  BerthRequestsRoute: typeof BerthRequestsRoute
  CapacityRoute: typeof CapacityRoute
  CargoRoute: typeof CargoRoute
  HazardousCargoRoute: typeof HazardousCargoRoute
  ImportRoute: typeof ImportRoute
  NotificationsRoute: typeof NotificationsRoute
  OperatorsRoute: typeof OperatorsRoute
  ReservationRoute: typeof ReservationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reservation': {
      id: '/reservation'
      path: '/reservation'
      fullPath: '/reservation'
      preLoaderRoute: typeof ReservationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operators': {
      id: '/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof OperatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hazardous-cargo': {
      id: '/hazardous-cargo'
      path: '/hazardous-cargo'
      fullPath: '/hazardous-cargo'
      preLoaderRoute: typeof HazardousCargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargo': {
      id: '/cargo'
      path: '/cargo'
      fullPath: '/cargo'
      preLoaderRoute: typeof CargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/capacity': {
      id: '/capacity'
      path: '/capacity'
      fullPath: '/capacity'
      preLoaderRoute: typeof CapacityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berth-requests': {
      id: '/berth-requests'
      path: '/berth-requests'
      fullPath: '/berth-requests'
      preLoaderRoute: typeof BerthRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berth-request-confirmation': {
      id: '/berth-request-confirmation'
      path: '/berth-request-confirmation'
      fullPath: '/berth-request-confirmation'
      preLoaderRoute: typeof BerthRequestConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berth-request-add': {
      id: '/berth-request-add'
      path: '/berth-request-add'
      fullPath: '/berth-request-add'
      preLoaderRoute: typeof BerthRequestAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/berth-manager': {
      id: '/berth-manager'
      path: '/berth-manager'
      fullPath: '/berth-manager'
      preLoaderRoute: typeof BerthManagerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  HazardousCargoManagerRoute: HazardousCargoManagerRoute,
  HazardousCargoRoute: HazardousCargoRoute,
  BerthManagerRoute: BerthManagerRoute,
  BerthRequestConfirmationRoute: BerthRequestConfirmationRoute,
  BerthRequestAddRoute: BerthRequestAddRoute,
  BerthRequestsRoute: BerthRequestsRoute,
  CapacityRoute: CapacityRoute,
  CargoRoute: CargoRoute,
  HazardousCargoRoute: HazardousCargoRoute,
  ImportRoute: ImportRoute,
  NotificationsRoute: NotificationsRoute,
  OperatorsRoute: OperatorsRoute,
  ReservationRoute: ReservationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/analytics",
        "/hazardous-cargo-manager",
        "/hazardous-cargo",
        "/berth-manager",
        "/berth-requests",
        "/capacity",
        "/cargo",
        "/import",
        "/notifications",
        "/operators",
        "/reservation",
        "/terminal-capacity"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/analytics": {
      "filePath": "analytics.tsx"
    },
    "/hazardous-cargo-manager": {
      "filePath": "hazardous-cargo-manager.tsx"
    },
    "/hazardous-cargo": {
      "filePath": "hazardous-cargo.tsx"
    },
    "/berth-manager": {
      "filePath": "berth-manager.tsx"
    },
    "/berth-requests": {
      "filePath": "berth-requests.tsx"
    },
    "/capacity": {
      "filePath": "capacity.tsx"
    },
    "/cargo": {
      "filePath": "cargo.tsx"
    },
    "/import": {
      "filePath": "import.tsx"
    },
    "/notifications": {
      "filePath": "notifications.tsx"
    },
    "/operators": {
      "filePath": "operators.tsx"
    },
    "/reservation": {
      "filePath": "reservation.tsx"
    },
    "/terminal-capacity": {
      "filePath": "terminal-capacity.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
